/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolManagement } from "./SchoolManagement";
export * as factories from "./factories";
export { SchoolManagement__factory } from "./factories/SchoolManagement__factory";
